# Generated by Django 3.1.1 on 2020-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter Surname', max_length=20)),
                ('location', models.CharField(help_text='Enter Location', max_length=20)),
                ('age', models.IntegerField(help_text='Enter Age', max_length=3)),
                ('shoe_size', models.IntegerField(help_text='Enter Shoe Size', max_length=2)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'age'],
            },
        ),
    ]
